In [1]:
# 연습문제 1번

l1 = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
print(l1)

['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']


In [2]:
# 연습문제 2번

l1 = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
for i in range(0,7):
  l2 = l1[i][0]
  print(l2)

월
화
수
목
금
토
일


In [3]:
# 연습문제 3번

print(dict(l1,l2))

TypeError: ignored

In [4]:
# 연습문제 4번

import numpy as np

a = np.eye(10) # 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성.
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
# 연습문제 5번

a_fliplr = np.fliplr(a)
print(a_fliplr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
c = a + a_fliplr
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [7]:
# 연습문제 6번

import collections, numpy
cUnique = numpy.array(c)
unique, counts = numpy.unique(cUnique, return_counts=True)
print(dict(zip(unique, counts)))

{0.0: 80, 1.0: 20}
