## 연습문제 1번
* 리스트에 모든 요일 입력(l1)

In [4]:
l1 = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
print(l1)

['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']


## 연습문제 2번
* 모든요일 l1에서 하나씩 뽑아서 '요일'자를 빼고 한글 (ex '월')로 만들어서  l2에 입력

In [ ]:

l1 = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
for i in range(0,7):
  l2 = l1[i][0]
  print(l2)

월
화
수
목
금
토
일


## 연습문제 3번
* (ex '월')을 '월요일'로 바꾸는 인코더를 만들것, l2로 l1을 만들것 (end dictionary {} 형태로)

## 연습문제 4번
* 대각선 1 나머지 0으로 채우는 10 x 10을 구현하는 2층의 list 만들기 (new)

In [9]:
import numpy as np

a = np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 연습문제 5번

위 4번의 list에 반대 방향으로 1 채우기 (update)

In [10]:
a_fliplr = np.fliplr(a)
print(a_fliplr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
c = a + a_fliplr
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# 연습문제 6번
* 5번의 결과에서 1의 갯수 찾기

In [12]:
import collections, numpy
cUnique = numpy.array(c)
unique, counts = numpy.unique(cUnique, return_counts=True)
print(dict(zip(unique, counts)))

{0.0: 80, 1.0: 20}
